-- ============================================================
-- Seed: nht_product_parameters - FULL IMPORT (extracted segment)
-- Notes: delete demo ids>=10000; REPLACE INTO overwrites duplicates/bad rows
-- ============================================================

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `nht_product_parameters` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
  `product_id` bigint NOT NULL DEFAULT '0' COMMENT '产品id',
  `options` varchar(255) COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '选择值',
  `param_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '参数名称',
  `param_type` int DEFAULT NULL COMMENT '参数类型（ 0输入框 ，1下拉框 ）',
  `required` char(2) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '是否必填（Y是 N否）',
  `sort` int DEFAULT NULL COMMENT '排序',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '删除标志（0代表存在 2代表删除）',
  `create_by` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=215 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='产品属性表';

-- ----------------------------

DELETE FROM nht_product_parameters WHERE id >= 10000;

REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (1, 2, '≥720,≥700,≥690', '容重(g/L)', 1, 'Y', 1, '0', '', '2025-12-19 16:34:54', '', '2025-12-19 20:25:54');
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (2, 2, '≤14.0,≤14.5', '水分', 1, 'Y', 2, '0', '', '2025-12-19 16:34:54', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (3, 2, '≤5.0,≤6.5', '不完善粒', 1, 'Y', 3, '0', '', '2025-12-19 16:34:54', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (4, 2, '≤1.0,≤2.0', '生霉粒', 1, 'Y', 4, '0', '', '2025-12-19 16:34:54', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (5, 2, '≥7.5,≥7.0', '粗蛋白', 1, 'Y', 5, '0', '', '2025-12-19 16:34:54', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (6, 2, '≤0.5', '杂质', 1, 'Y', 6, '0', '', '2025-12-19 16:34:54', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (7, 3, '≥760', '容重', 1, 'Y', 1, '0', '', '2025-12-19 16:34:56', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (8, 3, '≤14.0', '水分', 1, 'Y', 2, '0', '', '2025-12-19 16:34:56', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (9, 3, '≥12.0', '粗蛋白', 1, 'Y', 3, '0', '', '2025-12-19 16:34:56', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (10, 3, '≤8.0', '不完善粒', 1, 'Y', 4, '0', '', '2025-12-19 16:34:56', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (11, 3, '≤1.0', '生霉粒', 1, 'Y', 5, '0', '', '2025-12-19 16:34:56', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (12, 3, '≤1.0', '杂质', 1, 'Y', 6, '0', '', '2025-12-19 16:34:56', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (13, 4, '<14,<14.5,<15', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:34:58', '', '2025-12-19 20:22:37');
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (14, 4, '≥10.0,≥9.0', '粗蛋白', 1, 'Y', 2, '0', '', '2025-12-19 16:34:58', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (15, 4, '≥35,≥30', '千粒重', 1, 'Y', 3, '0', '', '2025-12-19 16:34:58', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (16, 4, '≤1.0,≤2.0', '霉变粒', 1, 'Y', 4, '0', '', '2025-12-19 16:34:58', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (17, 4, '≤5.0,≤5.5', '粗纤维', 1, 'Y', 5, '0', '', '2025-12-19 16:34:58', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (18, 4, '≤3.0', '粗灰分', 1, 'Y', 6, '0', '', '2025-12-19 16:34:58', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (19, 4, '≤80', '脂肪酸值', 1, 'Y', 7, '0', '', '2025-12-19 16:34:58', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (20, 5, '(5.1-9.1)≤14.0,≤14.5,其他≤14.5,≤15.0', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:35:00', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (21, 5, '≥13.0,≥11.0', '粗蛋白', 1, 'Y', 2, '0', '', '2025-12-19 16:35:00', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (22, 5, '≥750,≥730', '容重', 1, 'Y', 3, '0', '', '2025-12-19 16:35:00', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (23, 5, '≤1.0,≤2.0', '霉变粒', 1, 'Y', 4, '0', '', '2025-12-19 16:35:00', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (24, 5, '≤2.0,≤2.5', '粗纤维', 1, 'Y', 5, '0', '', '2025-12-19 16:35:00', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (25, 5, '≤2.0,≤2.5', '粗灰分', 1, 'Y', 6, '0', '', '2025-12-19 16:35:00', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (26, 5, '≤80', '脂肪酸值', 1, 'Y', 7, '0', '', '2025-12-19 16:35:00', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (27, 6, '夏≤14.0,冬≤15.0', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:35:03', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (28, 6, '≥6.0', '粗蛋白', 1, 'Y', 2, '0', '', '2025-12-19 16:35:03', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (29, 6, '≤2.0', '粗纤维', 1, 'Y', 3, '0', '', '2025-12-19 16:35:03', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (30, 6, '≤2.0', '粗灰分', 1, 'Y', 4, '0', '', '2025-12-19 16:35:03', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (31, 7, '≤15.0', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:35:05', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (32, 7, '≥7.5', '粗蛋白', 1, 'Y', 2, '0', '', '2025-12-19 16:35:05', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (33, 7, '≤1.0', '杂质', 1, 'Y', 3, '0', '', '2025-12-19 16:35:05', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (34, 8, '≤13.0,≤14.0', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:35:07', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (35, 8, '≥35.0,≥30.0', '面筋', 1, 'Y', 2, '0', '', '2025-12-19 16:35:07', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (36, 8, '≥14.0,≥12.5', '粗蛋白', 1, 'Y', 3, '0', '', '2025-12-19 16:35:07', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (37, 8, '≤3.0', '粗纤维', 1, 'Y', 4, '0', '', '2025-12-19 16:35:07', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (38, 9, '(2.1-10.31)≤14.0,其他≤14.5', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:35:09', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (39, 9, '≥15.0', '粗蛋白', 1, 'Y', 2, '0', '', '2025-12-19 16:35:09', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (40, 9, '≤6.0', '粗灰分', 1, 'Y', 3, '0', '', '2025-12-19 16:35:09', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (41, 9, '<12.0', '粗纤维', 1, 'Y', 4, '0', '', '2025-12-19 16:35:09', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (42, 10, '≤13.0', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:35:12', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (43, 10, '≥14.0', '粗蛋白', 1, 'Y', 2, '0', '', '2025-12-19 16:35:12', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (44, 10, '≤3.5', '粗纤维', 1, 'Y', 3, '0', '', '2025-12-19 16:35:12', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (45, 11, '(10.1-5.1)≤14.0,其他≤13.0', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:35:14', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (46, 11, '≥12.0,≥11.0', '粗蛋白', 1, 'Y', 2, '0', '', '2025-12-19 16:35:14', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (47, 11, '≥15.0,≥14.0', '粗脂肪', 1, 'Y', 3, '0', '', '2025-12-19 16:35:14', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (48, 11, '≤9.0', '粗灰分', 1, 'Y', 4, '0', '', '2025-12-19 16:35:14', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (49, 11, '≤9.0,≤10.0', '粗纤维', 1, 'Y', 5, '0', '', '2025-12-19 16:35:14', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (50, 12, '≤12.0,≤13.0', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:35:17', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (51, 12, '≥15.0,≥14.0', '粗蛋白', 1, 'Y', 2, '0', '', '2025-12-19 16:35:17', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (52, 12, '≤10.0,≤12.0', '粗灰分', 1, 'Y', 3, '0', '', '2025-12-19 16:35:17', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (53, 12, '≤8.0,≤10.0', '粗纤维', 1, 'Y', 4, '0', '', '2025-12-19 16:35:17', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (54, 13, '5-9月≤13.0,其他≤16.5', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:35:20', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (55, 13, '≥8.0', '粗蛋白', 1, 'Y', 2, '0', '', '2025-12-19 16:35:20', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (56, 13, '≤7.0', '粗灰分', 1, 'Y', 3, '0', '', '2025-12-19 16:35:20', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (57, 13, '≤10.0', '粗脂肪', 1, 'Y', 4, '0', '', '2025-12-19 16:35:20', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (58, 14, '≤13.0', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:35:23', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (59, 14, '≤8.0', '粗灰分', 1, 'Y', 2, '0', '', '2025-12-19 16:35:23', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (60, 14, '≥45.0', '淀粉', 1, 'Y', 3, '0', '', '2025-12-19 16:35:23', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (61, 14, '≤3.0', '含沙量', 1, 'Y', 4, '0', '', '2025-12-19 16:35:23', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (62, 15, '≥60.0,≥58.0,≥55.0', '粗蛋白', 1, 'Y', 1, '0', '', '2025-12-19 16:35:26', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (63, 15, '≤5.0,≤8.0', '水分', 1, 'Y', 2, '0', '', '2025-12-19 16:35:26', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (64, 15, '≤2.0', '粗灰分', 1, 'Y', 3, '0', '', '2025-12-19 16:35:26', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (65, 15, '≤10.0', '粗脂肪', 1, 'Y', 4, '0', '', '2025-12-19 16:35:26', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (66, 16, '≥24.0(高脂),≥27.0(低脂)', '粗蛋白', 1, 'Y', 1, '0', '', '2025-12-19 16:35:30', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (67, 16, '≤9.0', '水分', 1, 'Y', 2, '0', '', '2025-12-19 16:35:30', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (68, 16, '<58.0', '粗灰分', 1, 'Y', 3, '0', '', '2025-12-19 16:35:30', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (69, 16, '≥8.0(高脂),≥4.0(低脂)', '粗脂肪', 1, 'Y', 4, '0', '', '2025-12-19 16:35:30', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (70, 16, '≤12.0', '粗纤维', 1, 'Y', 5, '0', '', '2025-12-19 16:35:30', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (71, 17, '≥16.0,≥22.0', '粗蛋白', 1, 'Y', 1, '0', '', '2025-12-19 16:35:33', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (72, 17, '≤12.0', '水分', 1, 'Y', 2, '0', '', '2025-12-19 16:35:33', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (73, 17, '≥2.5', '粗灰分', 1, 'Y', 3, '0', '', '2025-12-19 16:35:34', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (74, 17, '≤6.0,≤8.0', '粗脂肪', 1, 'Y', 4, '0', '', '2025-12-19 16:35:34', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (75, 17, '≤8.0', '粗纤维', 1, 'Y', 5, '0', '', '2025-12-19 16:35:34', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (76, 19, '≤13.0', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:38:50', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (77, 19, '≥43.0(普),≥45.0(一),≥46.0(二)', '粗蛋白', 1, 'Y', 2, '0', '', '2025-12-19 16:38:50', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (78, 19, '≤7.0', '粗灰分', 1, 'Y', 3, '0', '', '2025-12-19 16:38:50', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (79, 19, '≥73.0(脱皮)', 'KOH溶解度', 1, 'Y', 4, '0', '', '2025-12-19 16:38:50', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (80, 19, '≤7.0', '粗纤维', 1, 'Y', 5, '0', '', '2025-12-19 16:38:50', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (81, 19, '≤0.30', '尿素酶', 1, 'Y', 6, '0', '', '2025-12-19 16:38:50', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (82, 20, '≤13.0', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:38:55', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (83, 20, '≥50.0,≥46.0,≥42.0', '粗蛋白', 1, 'Y', 2, '0', '', '2025-12-19 16:38:55', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (84, 20, '≤6.5', '粗灰分', 1, 'Y', 3, '0', '', '2025-12-19 16:38:55', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (85, 20, '60-70', 'KOH溶解度', 1, 'Y', 4, '0', '', '2025-12-19 16:38:55', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (86, 20, '≤10.0,≤11.0,≤14.0', '粗纤维', 1, 'Y', 5, '0', '', '2025-12-19 16:38:55', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (87, 20, '≤300,≤750,≤1200', '游离棉酚', 1, 'Y', 6, '0', '', '2025-12-19 16:38:55', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (88, 21, '≤10.0', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:38:59', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (89, 21, '≥55.0,≥50.0', '粗蛋白', 1, 'Y', 2, '0', '', '2025-12-19 16:38:59', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (90, 21, '≤6.5', '粗灰分', 1, 'Y', 3, '0', '', '2025-12-19 16:38:59', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (91, 21, '≤300.0', '游离棉酚', 1, 'Y', 4, '0', '', '2025-12-19 16:38:59', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (92, 21, '≤7.5', '粗纤维', 1, 'Y', 5, '0', '', '2025-12-19 16:38:59', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (93, 22, '≤13.0', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:39:03', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (94, 22, '≥36.0', '粗蛋白', 1, 'Y', 2, '0', '', '2025-12-19 16:39:03', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (95, 22, '≤8.0', '粗灰分', 1, 'Y', 3, '0', '', '2025-12-19 16:39:03', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (96, 22, '≤1.5', '粗脂肪', 1, 'Y', 4, '0', '', '2025-12-19 16:39:03', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (97, 22, '≤14.0', '粗纤维', 1, 'Y', 5, '0', '', '2025-12-19 16:39:04', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (98, 22, '≥36.0', 'KOH溶解度', 1, 'Y', 6, '0', '', '2025-12-19 16:39:04', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (99, 23, '≤12.0', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:39:08', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (100, 23, '≥37.0', '粗蛋白', 1, 'Y', 2, '0', '', '2025-12-19 16:39:08', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (101, 23, '≤8.0', '粗灰分', 1, 'Y', 3, '0', '', '2025-12-19 16:39:08', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (102, 23, '<28.0', '粗纤维', 1, 'Y', 4, '0', '', '2025-12-19 16:39:08', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (103, 24, '≤12.0', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:39:12', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (104, 24, '≥50.0,≥46.0', '粗蛋白', 1, 'Y', 2, '0', '', '2025-12-19 16:39:12', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (105, 24, '<7.0', '粗灰分', 1, 'Y', 3, '0', '', '2025-12-19 16:39:12', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (106, 24, '<9.0', '粗纤维', 1, 'Y', 4, '0', '', '2025-12-19 16:39:12', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (107, 25, '≤12.0', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:39:16', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (108, 25, '≥42.0', '粗蛋白', 1, 'Y', 2, '0', '', '2025-12-19 16:39:16', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (109, 25, '≤15.0', '粗灰分', 1, 'Y', 3, '0', '', '2025-12-19 16:39:16', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (110, 25, '≥48.0', 'CP+EE', 1, 'Y', 4, '0', '', '2025-12-19 16:39:16', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (111, 26, '≤12.0', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:39:20', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (112, 26, '≥14.0', '粗蛋白', 1, 'Y', 2, '0', '', '2025-12-19 16:39:20', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (113, 26, '<6.0', '粗灰分', 1, 'Y', 3, '0', '', '2025-12-19 16:39:20', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (114, 26, '<13.0', '粗纤维', 1, 'Y', 4, '0', '', '2025-12-19 16:39:20', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (115, 28, '≤0.2', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:40:42', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (116, 28, '≤4.0', '酸价', 1, 'Y', 2, '0', '', '2025-12-19 16:40:42', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (117, 28, '≤1.5', '不皂化', 1, 'Y', 3, '0', '', '2025-12-19 16:40:42', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (118, 29, '≤0.2(夏),0.5(冬)', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:40:45', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (119, 29, '≤8.0', '酸价', 1, 'Y', 2, '0', '', '2025-12-19 16:40:45', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (120, 29, '≤2.8', '不皂化', 1, 'Y', 3, '0', '', '2025-12-19 16:40:45', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (121, 30, '0.2(夏),0.5(冬)', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:40:49', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (122, 30, '≤3.0', '酸价', 1, 'Y', 2, '0', '', '2025-12-19 16:40:49', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (123, 30, '≤2.5', '不皂化', 1, 'Y', 3, '0', '', '2025-12-19 16:40:49', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (124, 31, '≤1.0', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:40:52', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (125, 31, '≤50.0', '酸价', 1, 'Y', 2, '0', '', '2025-12-19 16:40:52', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (126, 31, '≤5.0', '不皂化', 1, 'Y', 3, '0', '', '2025-12-19 16:40:52', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (127, 32, '≤1.0', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:40:55', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (128, 32, '≤45.0', '酸价', 1, 'Y', 2, '0', '', '2025-12-19 16:40:55', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (129, 32, '≤2.5', '不皂化', 1, 'Y', 3, '0', '', '2025-12-19 16:40:55', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (130, 33, '≤0.25', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:40:58', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (131, 33, '≤4.0(夏),3.0(冬)', '酸价', 1, 'Y', 2, '0', '', '2025-12-19 16:40:58', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (132, 33, '≤2.5', '不皂化', 1, 'Y', 3, '0', '', '2025-12-19 16:40:58', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (133, 34, '≤0.25', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:41:01', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (134, 34, '≤3.0', '酸价', 1, 'Y', 2, '0', '', '2025-12-19 16:41:01', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (135, 34, '≤2.5', '不皂化', 1, 'Y', 3, '0', '', '2025-12-19 16:41:01', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (136, 36, '≤12.0', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:42:26', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (137, 36, '≥45.0', '粗蛋白', 1, 'Y', 2, '0', '', '2025-12-19 16:42:26', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (138, 36, '≤8.0', '粗灰分', 1, 'Y', 3, '0', '', '2025-12-19 16:42:26', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (139, 36, '≤5.0', '粗纤维', 1, 'Y', 4, '0', '', '2025-12-19 16:42:26', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (140, 36, '≤11', '非蛋白氮', 1, 'Y', 5, '0', '', '2025-12-19 16:42:26', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (141, 37, '≤10.0', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:42:30', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (142, 37, '≥40.0', '粗蛋白', 1, 'Y', 2, '0', '', '2025-12-19 16:42:30', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (143, 37, '≤14.0', '粗灰分', 1, 'Y', 3, '0', '', '2025-12-19 16:42:30', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (144, 37, '64-87', '胃蛋白酶消化率', 1, 'Y', 4, '0', '', '2025-12-19 16:42:30', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (145, 38, '≤8.0', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:42:33', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (146, 38, '≥60.0', '粗蛋白', 1, 'Y', 2, '0', '', '2025-12-19 16:42:33', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (147, 38, '≤10.0', '粗灰分', 1, 'Y', 3, '0', '', '2025-12-19 16:42:33', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (148, 38, '≥65', 'TP/CP', 1, 'Y', 4, '0', '', '2025-12-19 16:42:33', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (149, 39, '≤10.0', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:42:37', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (150, 39, '≥65.0', '粗蛋白', 1, 'Y', 2, '0', '', '2025-12-19 16:42:37', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (151, 39, '≤5.0,6.0', '粗灰分', 1, 'Y', 3, '0', '', '2025-12-19 16:42:37', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (152, 39, '≥10.0,8.0', '苏氨酸', 1, 'Y', 4, '0', '', '2025-12-19 16:42:37', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (153, 40, '≤13.0', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:42:40', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (154, 40, '≥65.0', '粗蛋白', 1, 'Y', 2, '0', '', '2025-12-19 16:42:40', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (155, 40, '≤4.0', '粗灰分', 1, 'Y', 3, '0', '', '2025-12-19 16:42:40', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (156, 40, '≥50.0', 'TP/CP', 1, 'Y', 4, '0', '', '2025-12-19 16:42:40', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (157, 42, '≤10.0', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:42:47', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (158, 42, '≥68.0(S),≥67.0(P),≥64.0(1),≥60.0(2)', '粗蛋白', 1, 'Y', 2, '0', '', '2025-12-19 16:42:47', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (159, 42, '≤16.5-20.0', '粗灰分', 1, 'Y', 3, '0', '', '2025-12-19 16:42:47', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (160, 42, '≤9.0-14.0', 'EE', 1, 'Y', 4, '0', '', '2025-12-19 16:42:47', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (161, 42, '≤4.0,≤5.0', '盐', 1, 'Y', 5, '0', '', '2025-12-19 16:42:47', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (162, 42, '2.5-6.0', '钙', 1, 'Y', 6, '0', '', '2025-12-19 16:42:47', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (163, 42, '≥1.8-2.0', '总磷', 1, 'Y', 7, '0', '', '2025-12-19 16:42:47', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (164, 43, '≥65.0', '粗蛋白', 1, 'Y', 1, '0', '', '2025-12-19 16:42:50', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (165, 43, '≤16.0', '粗脂肪', 1, 'Y', 2, '0', '', '2025-12-19 16:42:50', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (166, 43, '≤10.0', '粗灰分', 1, 'Y', 3, '0', '', '2025-12-19 16:42:50', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (167, 43, '≤7.0', '酸价', 1, 'Y', 4, '0', '', '2025-12-19 16:42:50', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (168, 43, '≤2.0', '总磷', 1, 'Y', 5, '0', '', '2025-12-19 16:42:50', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (169, 44, '≤10.0', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:42:52', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (170, 44, '≤12.0-15.0', '粗脂肪', 1, 'Y', 2, '0', '', '2025-12-19 16:42:52', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (171, 44, '≤30.0-43.0', '粗灰分', 1, 'Y', 3, '0', '', '2025-12-19 16:42:52', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (172, 44, '.0-15.0', '钙', 1, 'Y', 4, '0', '', '2025-12-19 16:42:52', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (173, 44, '≤3.5-4.0', '总磷', 1, 'Y', 5, '0', '', '2025-12-19 16:42:52', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (174, 44, '≤5.0-9.0', '酸价', 1, 'Y', 6, '0', '', '2025-12-19 16:42:52', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (175, 44, '≤50.0', 'VBN', 1, 'Y', 7, '0', '', '2025-12-19 16:42:52', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (176, 45, '≤8.0', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:42:55', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (177, 45, '≥85.0(1),≥80.0(2)', '粗蛋白', 1, 'Y', 2, '0', '', '2025-12-19 16:42:55', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (178, 45, '≤7.0', '粗脂肪', 1, 'Y', 3, '0', '', '2025-12-19 16:42:55', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (179, 45, '≤3.0,≤6.0', '粗灰分', 1, 'Y', 4, '0', '', '2025-12-19 16:42:55', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (180, 45, '≥75.0', '胃消化率', 1, 'Y', 5, '0', '', '2025-12-19 16:42:55', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (181, 45, '≤200.0', 'VBN', 1, 'Y', 6, '0', '', '2025-12-19 16:42:55', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (182, 46, '≥16.0', '总磷', 1, 'Y', 1, '0', '', '2025-12-19 16:42:57', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (183, 46, '≥21.0', '钙', 1, 'Y', 2, '0', '', '2025-12-19 16:42:57', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (184, 46, '≤75', '灰分', 1, 'Y', 3, '0', '', '2025-12-19 16:42:57', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (185, 47, '≤8.0', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:43:00', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (186, 47, '≥75.0(猪),≥65.0(鸭)', '粗蛋白', 1, 'Y', 2, '0', '', '2025-12-19 16:43:00', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (187, 47, '≤10.0(猪),≤15.0(鸭)', '粗灰分', 1, 'Y', 3, '0', '', '2025-12-19 16:43:00', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (188, 47, '≤35.0', 'VBN', 1, 'Y', 4, '0', '', '2025-12-19 16:43:00', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (189, 47, '≥15.0(猪),≥10.0(鸭)', 'IgG', 1, 'Y', 5, '0', '', '2025-12-19 16:43:00', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (190, 48, '≤10.0', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:43:02', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (191, 48, '≥90.0', '粗蛋白', 1, 'Y', 2, '0', '', '2025-12-19 16:43:02', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (192, 48, '≤5.0', '粗灰分', 1, 'Y', 3, '0', '', '2025-12-19 16:43:02', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (193, 48, '≤1.0', '粗脂肪', 1, 'Y', 4, '0', '', '2025-12-19 16:43:02', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (194, 48, '≤1.0', '酸价', 1, 'Y', 5, '0', '', '2025-12-19 16:43:02', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (195, 48, '≤50.0', 'VBN', 1, 'Y', 6, '0', '', '2025-12-19 16:43:02', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (196, 48, '≥90.0', 'TP/CP', 1, 'Y', 7, '0', '', '2025-12-19 16:43:02', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (197, 50, '≥19', '总磷', 1, 'Y', 1, '0', '', '2025-12-19 16:43:33', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (198, 50, '≥28', '钙', 1, 'Y', 2, '0', '', '2025-12-19 16:43:33', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (199, 50, '≥14', '枸溶磷', 1, 'Y', 3, '0', '', '2025-12-19 16:43:33', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (200, 51, '≥36.0', '钙', 1, 'Y', 1, '0', '', '2025-12-19 16:43:34', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (201, 51, '≤400.0', '氟', 1, 'Y', 2, '0', '', '2025-12-19 16:43:34', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (202, 51, '≤10.0', '铅', 1, 'Y', 3, '0', '', '2025-12-19 16:43:34', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (203, 51, '≤2.0', '砷', 1, 'Y', 4, '0', '', '2025-12-19 16:43:35', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (204, 52, '≥100.0,≥90.0', '吸氨值', 1, 'Y', 1, '0', '', '2025-12-19 16:43:36', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (205, 52, '≤14.0,≤16.0', '干燥失重', 1, 'Y', 2, '0', '', '2025-12-19 16:43:36', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (206, 53, '≤12.0', '水分', 1, 'Y', 1, '0', '', '2025-12-19 16:43:38', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (207, 53, '≥55.0', '腐植酸:', 1, 'Y', 2, '0', '', '2025-12-19 16:43:38', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (208, 55, '≥16.5,≥19.0,≥21.0', '总磷', 1, 'Y', 1, '0', '', '2025-12-19 16:44:12', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (209, 55, '≥14.0,≥16.0,≥18.0', '枸溶磷', 1, 'Y', 2, '0', '', '2025-12-19 16:44:12', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (210, 55, '≥8.0,≥10.0', '水溶磷', 1, 'Y', 3, '0', '', '2025-12-19 16:44:12', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (211, 55, '≥20.0,≥15.0,≥14.0', '钙', 1, 'Y', 4, '0', '', '2025-12-19 16:44:12', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (212, 56, '≥22.0', '总磷', 1, 'Y', 1, '0', '', '2025-12-19 16:44:14', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (213, 56, '≥20.0', '水溶磷', 1, 'Y', 2, '0', '', '2025-12-19 16:44:14', '', NULL);
REPLACE INTO `nht_product_parameters` (`id`, `product_id`, `options`, `param_name`, `param_type`, `required`, `sort`, `del_flag`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES (214, 56, '≥13.0', '钙', 1, 'Y', 3, '0', '', '2025-12-19 16:44:14', '', NULL);

